name:                simple-gdk3
version:             0.1.0.0
github:              "githubuser/simple-gdk3"
license:             BSD3
author:              "Author name here"
maintainer:          "example@example.com"
copyright:           "2021 Author name here"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/simple-gdk3#readme>

dependencies:
- base >= 4.7 && < 5
- primitive
- exception-hierarchy
- c-enum
- c-struct
- simple-cairo
- glib-stopgap

library:
  source-dirs: src
  pkg-config-dependencies: gdk-3.0
  include-dirs: include
  exposed-modules:
  - Graphics.Gdk.Cursors
  - Graphics.Gdk.Cursors.Internal
  - Graphics.Gdk.EventStructures
  - Graphics.Gdk.EventStructures.GdkEventType
  - Graphics.Gdk.EventStructures.GdkKeySyms
  - Graphics.Gdk.EventStructures.Internal
  - Graphics.Gdk.Events
  - Graphics.Gdk.Exception
  - Graphics.Gdk.GdkDevice
  - Graphics.Gdk.GdkDevice.GdkAxes
  - Graphics.Gdk.GdkDevice.GdkAxes.Internal
  - Graphics.Gdk.GdkDevice.Internal
  - Graphics.Gdk.GdkDisplay
  - Graphics.Gdk.GdkDisplay.Internal
  - Graphics.Gdk.GdkDisplayManager
  - Graphics.Gdk.GdkDisplayManager.Internal
  - Graphics.Gdk.GdkDrawingContext
  - Graphics.Gdk.GdkDrawingContext.Internal
  - Graphics.Gdk.GdkMonitor
  - Graphics.Gdk.GdkMonitor.Internal
  - Graphics.Gdk.GdkScreen
  - Graphics.Gdk.GdkScreen.Internal
  - Graphics.Gdk.GdkSeat
  - Graphics.Gdk.GdkSeat.Internal
  - Graphics.Gdk.General
  - Graphics.Gdk.PointsAndRectangles
  - Graphics.Gdk.PointsAndRectangles.Internal
  - Graphics.Gdk.PropertiesAndAtoms.GdkAtom
  - Graphics.Gdk.Visuals
  - Graphics.Gdk.Visuals.Internal
  - Graphics.Gdk.Windows
  - Graphics.Gdk.Windows.GdkEventMask
  - Graphics.Gdk.Windows.GdkEventMask.Internal
  - Graphics.Gdk.Windows.GdkModifierType
  - Graphics.Gdk.Windows.GdkWindowAttr
  - Graphics.Gdk.Windows.GdkWindowAttr.Internal
  - Graphics.Gdk.Windows.Internal

tests:
  simple-gdk3-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - simple-gdk3
